### ISSUE TITLE
Choose API architecture and framework (Bb#2)

### ISSUE THREAD

**Issue by patrickcapaldo** [patrickcap/APAQ#1]
Given that the user is a developer who will integrate this tool into their software, an API is the selected method for them to interact with this tool. However, the architecture and framework for this API must be selected.

Done:
- Research has been completed for a handful of possible APIs architectures (e.g., REST, SOAP, RPC) and frameworks (e.g., Flask, Django REST, ...)
- Considered the chosen programming language for the APAQ tool
- Reasoning documented

**Comment by patrickxcapaldo** [comment]
Given that the user is a developer who will integrate this tool into their software, an API is the selected method for them to interact with this tool. However, the architecture and framework for this API must be selected.

Done:
- Research has been completed for a handful of possible APIs architectures (e.g., REST, SOAP, RPC) and frameworks (e.g., Flask, Django REST, ...)
- Considered the chosen programming language for the APAQ tool
