### ISSUE TITLE
Data preparation: OpenAQ

### ISSUE THREAD

**Issue by patrickcapaldo** [patrickcap/APAQ#10]
Experiment with OpenAQ API to retrieve air quality measurements within a radius of a particular long/lat location.

Done:
- provide long/lat of an airport to a Python script, returns the closest AQ measurement to this location if there is one within a particular threshold.

**Comment by patrickxcapaldo** [comment]
Ending up finding pm10 data using OpenWeather for a large dataset (new) and small dataset (original)
