### ISSUE TITLE
Combine augmented images and air quality measurements (Bb#7)

### ISSUE THREAD

**Issue by patrickcapaldo** [patrickcap/APAQ#8]
Once all satellite images have been augmented to extract only the important features for training, they still must be combined with the air quality data and stored as one dataset.

Done:

- Augmented images are linked to their associated air quality measurements and stored in a single database that can be accessed easily by the chosen programming language
- Method to access these images is documented

**Comment by patrickxcapaldo** [comment]
Once all satellite images have been augmented to extract only the important features for training, they still must be combined with the air quality data and stored as one dataset.

Done:
- Augmented images are linked to their associated air quality measurements and stored in a single database that can be accessed easily by the chosen programming language
- Method to access these images is documented
